name: HRKChat
main: CortexPE\HRKChat\Main
version: 1.0.0
api: 3.0.0
load: POSTWORLD
author: CortexPE
description: Chat & nametag formatter that respects Role Hierarchy
website: https://CortexPE.xyz
depends: ["Hierarchy"]