name: HRKChat
main: CortexPE\HRKChat\HRKChat
version: 1.1.2
api: 4.0.0
load: POSTWORLD
author: CortexPE
description: Chat & nametag formatter that respects Role Hierarchy
website: https://CortexPE.xyz
depend: ["Hierarchy"]
softdepend: ["Hierarchy"]